using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Perfectum
{
    class Werkwoorden
    {
        public List<Werkwoord> WerkwoordenList;

        public Werkwoorden()
        {
            WerkwoordenList = new List<Werkwoord>
            {
                new Werkwoord("eten", "gegeten"),
                new Werkwoord("gebruiken", "gebruikt"),
                new Werkwoord("liggen", "gelegen"),
                new Werkwoord("kosten", "gekost"),
                new Werkwoord("dragen", "gedragen"),
                new Werkwoord("legen", "geleegd"),
                new Werkwoord("vullen", "gevuld"),
                new Werkwoord("douchen", "gedoucht"),
                new Werkwoord("terugbrengen", "teruggebracht"),
                new Werkwoord("scheiden", "gescheiden (zijn)"),
                new Werkwoord("huwen", "huwden (zijn)"),
                new Werkwoord("drinken", "gedronken"),
                new Werkwoord("helpen", "geholpen"),
                new Werkwoord("brengen", "gebracht"),
                new Werkwoord("poetsen", "gepoetst"),
                new Werkwoord("opstaan", "opgestaan (zijn)"),
                new Werkwoord("halen", "gehaald"),
                new Werkwoord("doen", "gedaan"),
                new Werkwoord("werken", "gewerkt"),
                new Werkwoord("lunchen", "geluncht"),
                new Werkwoord("kijken", "gekeken"),
                new Werkwoord("maken", "gemaakt"),
                new Werkwoord("spelen", "gespeeld"),
                new Werkwoord("afspreken", "afgesproken"),
                new Werkwoord("telefoneren", "getelefoneerd"),
                new Werkwoord("slapen", "geslapen"),
                new Werkwoord("zoeken", "gezocht"),
                new Werkwoord("nemen", "genomen"),
                new Werkwoord("wachten", "gewacht"),
                new Werkwoord("geven", "gegeven"),
                new Werkwoord("bezoeken", "bezocht"),
                new Werkwoord("kopen", "gekocht"),
                new Werkwoord("gaan", "gegaan"),
                new Werkwoord("horen", "gehoord"),
                new Werkwoord("krijgen", "gekregen"),
                new Werkwoord("aandoen", "aangedaan"),
                new Werkwoord("wassen (zich)", "gewassen"),
                new Werkwoord("uitdoen", "uitgedaan"),
                new Werkwoord("stofzuigen", "gestofzuigd"),
                new Werkwoord("eten", "gegeten"),
                new Werkwoord("thuiskomen", "thuisgekomen"),
                new Werkwoord("vinden", "gevonden"),
                new Werkwoord("sturen", "gestuurd"),
                new Werkwoord("studeren", "gestudeerd"),
                new Werkwoord("drinken", "gedronken"),
                new Werkwoord("vergeten", "vergeten"),
                new Werkwoord("betalen", "betaald"),
                new Werkwoord("hebben", "gehad"),
                new Werkwoord("rijden", "gereden"),
                new Werkwoord("rijden naar", "gereden (zijn)"),
                new Werkwoord("zien", "gezien"),
                new Werkwoord("zeggen", "gezegd"),
                new Werkwoord("aankomen", "aangekomen"),
                new Werkwoord("vertrekken", "vertrokken (zijn)"),
                new Werkwoord("bellen", "gebeld"),
                new Werkwoord("vertellen", "verteld"),
                new Werkwoord("zijn", "geweest"),
                new Werkwoord("blijven", "gebleven (zijn)"),
                new Werkwoord("praten", "gepraat"),
                new Werkwoord("parkeren", "geparkeerd"),
                new Werkwoord("solliciteren", "gesolliciteerd"),
                new Werkwoord("wonen", "gewoond"),
                new Werkwoord("komen", "gekomen (zijn)"),
                new Werkwoord("verhuizen", "verhuisd (zijn)"),
                new Werkwoord("trouwen", "getrouwd (zijn)"),
                new Werkwoord("spreken", "gesproken"),
                new Werkwoord("luisteren", "geluisterd"),
                new Werkwoord("leren", "geleerd"),
                new Werkwoord("begrijpen", "begrepen"),
                new Werkwoord("schrijven", "geschreven"),
                new Werkwoord("lezen", "gelezen"),
                new Werkwoord("worden", "geworden"),
                new Werkwoord("instappen", "ingestapt (zijn)"),
                new Werkwoord("opstappen", "opgestapt (zijn)"),
                new Werkwoord("overstappen", "overgestapt (zijn)"),
                new Werkwoord("uitstappen", "uitgestapt (zijn)"),
                new Werkwoord("afstappen", "afgestapt (zijn)"),
                new Werkwoord("bakken", "gebakken"),
                new Werkwoord("koken", "gekookt"),
                new Werkwoord("meenemen", "meegenomen"),
                new Werkwoord("zingen", "gezongen"),
                new Werkwoord("wandelen", "gewandeld"),
                new Werkwoord("wandelen naar", "gewandeld (zijn)"),
                new Werkwoord("vallen", "gevallen (zijn)"),
                new Werkwoord("strijken", "gestreken"),
                new Werkwoord("ontbijten", "ontbeten"),
                new Werkwoord("dineren", "gedineerd"),
                new Werkwoord("weggaan", "weggegaan (zijn)"),
                new Werkwoord("meegaan", "meegegaan (zijn)"),
                new Werkwoord("verdrinken", "verdronken (zijn)"),
                new Werkwoord("streven", "gestreefd (zijn)"),
                new Werkwoord("huren", "gehuurd"),
                new Werkwoord("stappen", "gestapt"),
                new Werkwoord("stappen naar", "gestapt (zijn)"),
                new Werkwoord("verjaren", "verjaard (zijn)"),
                new Werkwoord("vliegen", "gevlogen"),
                new Werkwoord("vliegen naar", "gevlogen (zijn)"),
                new Werkwoord("fietsen", "gefietst"),
                new Werkwoord("stoppen", "gestopt"),
                new Werkwoord("fietsen naar", "gefietst (zijn)"),
                new Werkwoord("lopen", "gelopen"),
                new Werkwoord("lopen naar", "gelopen (zijn)"),
                new Werkwoord("beginnen", "begonnen (zijn)"),
                new Werkwoord("verstaan", "verstaan"),
            };
        }

    }
}
